perf_counter.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include `cmsis_compiler.h`
#include `perf_counter.h`
Data Structures
struct SysTick_Type
Structure type to access the System Timer (SysTick).
struct SCB_Type
Structure type to access the System Control Block (SCB).
struct __task_cycle_info_t
Macros
#define __IMPLEMENT_PERF_COUNTER
#define PERF_CNT_COMPENSATION_THRESHOLD 16
#define PERF_CNT_DELAY_US_COMPENSATION 90
#define __I volatile const
#define __O volatile
#define __IO volatile
#define __IM volatile const /*! Defines 'read only' structure member permissions */
#define __OM volatile /*! Defines 'write only' structure member permissions */
#define __IOM volatile /*! Defines 'read / write' structure member permissions */
#define SCS_BASE (0xE000E000UL)
#define SysTick_BASE (SCS_BASE + 0x0010UL)
#define SCB_BASE (SCS_BASE + 0x0D00UL)
#define SysTick ((SysTick_Type *) SysTick_BASE)
#define SCB ((SCB_Type *) SCB_BASE)
#define SysTick_CTRL_COUNTFLAG_Pos 16U
#define SysTick_CTRL_COUNTFLAG_Msk (1UL << SysTick_CTRL_COUNTFLAG_Pos)
#define SysTick_CTRL_CLKSOURCE_Pos 2U
#define SysTick_CTRL_CLKSOURCE_Msk (1UL << SysTick_CTRL_CLKSOURCE_Pos)
#define SysTick_CTRL_TICKINT_Pos 1U
#define SysTick_CTRL_TICKINT_Msk (1UL << SysTick_CTRL_TICKINT_Pos)
#define SysTick_CTRL_ENABLE_Pos 0U
#define SysTick_CTRL_ENABLE_Msk (1UL /*<< SysTick_CTRL_ENABLE_Pos*/)
#define SysTick_LOAD_RELOAD_Pos 0U
#define SysTick_LOAD_RELOAD_Msk (0xFFFFFFUL /*<< SysTick_LOAD_RELOAD_Pos*/)
#define SysTick_VAL_CURRENT_Pos 0U
#define SysTick_VAL_CURRENT_Msk (0xFFFFFFUL /*<< SysTick_VAL_CURRENT_Pos*/)
#define SysTick_CALIB_NOREF_Pos 31U
#define SysTick_CALIB_NOREF_Msk (1UL << SysTick_CALIB_NOREF_Pos)
#define SysTick_CALIB_SKEW_Pos 30U
#define SysTick_CALIB_SKEW_Msk (1UL << SysTick_CALIB_SKEW_Pos)
#define SysTick_CALIB_TENMS_Pos 0U
#define SysTick_CALIB_TENMS_Msk (0xFFFFFFUL /*<< SysTick_CALIB_TENMS_Pos*/)
#define SCB_ICSR_PENDSTCLR_Pos 25U
#define SCB_ICSR_PENDSTCLR_Msk (1UL << SCB_ICSR_PENDSTCLR_Pos)
#define SCB_ICSR_PENDSTSET_Pos 26U
#define SCB_ICSR_PENDSTSET_Msk (1UL << SCB_ICSR_PENDSTSET_Pos)
#define MAGIC_WORD_AGENT_LIST_VALID 0x8492A53C
#define MAGIC_WORD_CANARY 0xDEADBEEF
Functions
__STATIC_INLINE uint32_t SysTick_Config (uint32_t ticks)
System Tick Configuration.
void user_code_insert_to_systick_handler (void)
__WEAK void __perf_os_patch_init (void)
void init_cycle_counter (bool bIsSysTickOccupied)
initialise cycle counter service
bool start_cycle_counter (void)
try to set a start pointer for the performance counter
__STATIC_INLINE int32_t check_systick (void)
int32_t stop_cycle_counter (void)
calculate the elapsed cycle count since the last start point
void delay_us (int32_t nUs)
delay specified time in microsecond
void delay_ms (int32_t nMs)
delay specified time in millisecond
int64_t get_system_ticks (void)
get the elapsed cycles since perf_counter is initialised
int32_t get_system_ms (void)
get the elapsed milliseconds since perf_counter is initialised
__WEAK task_cycle_info_t * get_rtos_task_cycle_info (void)
void init_task_cycle_counter (void)
task_cycle_info_t * init_task_cycle_info (task_cycle_info_t *ptInfo)
bool enable_task_cycle_info (task_cycle_info_t *ptInfo)
bool disable_task_cycle_info (task_cycle_info_t *ptInfo)
void resume_task_cycle_info (task_cycle_info_t *ptInfo, bool bEnabledStatus)
task_cycle_info_agent_t * register_task_cycle_agent (task_cycle_info_t *ptInfo, task_cycle_info_agent_t *ptAgent)
task_cycle_info_agent_t * unregister_task_cycle_agent (task_cycle_info_agent_t *ptAgent)
void __on_context_switch_in (uint32_t *pwStack)
void __on_context_switch_out (uint32_t *pwStack)
void __start_task_cycle_counter (task_cycle_info_t *ptInfo)
int64_t __stop_task_cycle_counter (task_cycle_info_t *ptInfo)
Variables
uint32_t SystemCoreClock
Macro Definition Documentation
__I
#define __I volatile const
Defines 'read only' permissions
Definition at line 53 of file perf_counter.c.
__IM
#define __IM volatile const /*! Defines 'read only' structure member permissions */
Definition at line 59 of file perf_counter.c.
__IMPLEMENT_PERF_COUNTER
#define __IMPLEMENT_PERF_COUNTER
Definition at line 24 of file perf_counter.c.
__IO
#define __IO volatile
Defines 'read / write' permissions
Definition at line 56 of file perf_counter.c.
__IOM
#define __IOM volatile /*! Defines 'read / write' structure member permissions */
Definition at line 61 of file perf_counter.c.
__O
#define __O volatile
Defines 'write only' permissions
Definition at line 55 of file perf_counter.c.
__OM
#define __OM volatile /*! Defines 'write only' structure member permissions */
Definition at line 60 of file perf_counter.c.
MAGIC_WORD_AGENT_LIST_VALID
#define MAGIC_WORD_AGENT_LIST_VALID 0x8492A53C
Definition at line 111 of file perf_counter.c.
MAGIC_WORD_CANARY
#define MAGIC_WORD_CANARY 0xDEADBEEF
Definition at line 112 of file perf_counter.c.
PERF_CNT_COMPENSATION_THRESHOLD
#define PERF_CNT_COMPENSATION_THRESHOLD 16
Definition at line 34 of file perf_counter.c.
PERF_CNT_DELAY_US_COMPENSATION
#define PERF_CNT_DELAY_US_COMPENSATION 90
Definition at line 38 of file perf_counter.c.
SCB
#define SCB ((SCB_Type *) SCB_BASE)
SCB configuration struct
Definition at line 69 of file perf_counter.c.
SCB_BASE
#define SCB_BASE (SCS_BASE + 0x0D00UL)
System Control Block Base Address
Definition at line 66 of file perf_counter.c.
SCB_ICSR_PENDSTCLR_Msk
#define SCB_ICSR_PENDSTCLR_Msk (1UL << SCB_ICSR_PENDSTCLR_Pos)
SCB ICSR: PENDSTCLR Mask
Definition at line 105 of file perf_counter.c.
SCB_ICSR_PENDSTCLR_Pos
#define SCB_ICSR_PENDSTCLR_Pos 25U
SCB ICSR: PENDSTCLR Position
Definition at line 104 of file perf_counter.c.
SCB_ICSR_PENDSTSET_Msk
#define SCB_ICSR_PENDSTSET_Msk (1UL << SCB_ICSR_PENDSTSET_Pos)
SCB ICSR: PENDSTSET Mask
Definition at line 108 of file perf_counter.c.
SCB_ICSR_PENDSTSET_Pos
#define SCB_ICSR_PENDSTSET_Pos 26U
SCB ICSR: PENDSTSET Position
Definition at line 107 of file perf_counter.c.
SCS_BASE
#define SCS_BASE (0xE000E000UL)
System Control Space Base Address
Definition at line 64 of file perf_counter.c.
SysTick
#define SysTick ((SysTick_Type *) SysTick_BASE)
SysTick configuration struct
Definition at line 68 of file perf_counter.c.
SysTick_BASE
#define SysTick_BASE (SCS_BASE + 0x0010UL)
SysTick Base Address
Definition at line 65 of file perf_counter.c.
SysTick_CALIB_NOREF_Msk
#define SysTick_CALIB_NOREF_Msk (1UL << SysTick_CALIB_NOREF_Pos)
SysTick CALIB: NOREF Mask
Definition at line 94 of file perf_counter.c.
SysTick_CALIB_NOREF_Pos
#define SysTick_CALIB_NOREF_Pos 31U
SysTick CALIB: NOREF Position
Definition at line 93 of file perf_counter.c.
SysTick_CALIB_SKEW_Msk
#define SysTick_CALIB_SKEW_Msk (1UL << SysTick_CALIB_SKEW_Pos)
SysTick CALIB: SKEW Mask
Definition at line 97 of file perf_counter.c.
SysTick_CALIB_SKEW_Pos
#define SysTick_CALIB_SKEW_Pos 30U
SysTick CALIB: SKEW Position
Definition at line 96 of file perf_counter.c.
SysTick_CALIB_TENMS_Msk
#define SysTick_CALIB_TENMS_Msk (0xFFFFFFUL /*<< SysTick_CALIB_TENMS_Pos*/)
SysTick CALIB: TENMS Mask
Definition at line 100 of file perf_counter.c.
SysTick_CALIB_TENMS_Pos
#define SysTick_CALIB_TENMS_Pos 0U
SysTick CALIB: TENMS Position
Definition at line 99 of file perf_counter.c.
SysTick_CTRL_CLKSOURCE_Msk
#define SysTick_CTRL_CLKSOURCE_Msk (1UL << SysTick_CTRL_CLKSOURCE_Pos)
SysTick CTRL: CLKSOURCE Mask
Definition at line 76 of file perf_counter.c.
SysTick_CTRL_CLKSOURCE_Pos
#define SysTick_CTRL_CLKSOURCE_Pos 2U
SysTick CTRL: CLKSOURCE Position
Definition at line 75 of file perf_counter.c.
SysTick_CTRL_COUNTFLAG_Msk
#define SysTick_CTRL_COUNTFLAG_Msk (1UL << SysTick_CTRL_COUNTFLAG_Pos)
SysTick CTRL: COUNTFLAG Mask
Definition at line 73 of file perf_counter.c.
SysTick_CTRL_COUNTFLAG_Pos
#define SysTick_CTRL_COUNTFLAG_Pos 16U
SysTick CTRL: COUNTFLAG Position
Definition at line 72 of file perf_counter.c.
SysTick_CTRL_ENABLE_Msk
#define SysTick_CTRL_ENABLE_Msk (1UL /*<< SysTick_CTRL_ENABLE_Pos*/)
SysTick CTRL: ENABLE Mask
Definition at line 82 of file perf_counter.c.
SysTick_CTRL_ENABLE_Pos
#define SysTick_CTRL_ENABLE_Pos 0U
SysTick CTRL: ENABLE Position
Definition at line 81 of file perf_counter.c.
SysTick_CTRL_TICKINT_Msk
#define SysTick_CTRL_TICKINT_Msk (1UL << SysTick_CTRL_TICKINT_Pos)
SysTick CTRL: TICKINT Mask
Definition at line 79 of file perf_counter.c.
SysTick_CTRL_TICKINT_Pos
#define SysTick_CTRL_TICKINT_Pos 1U
SysTick CTRL: TICKINT Position
Definition at line 78 of file perf_counter.c.
SysTick_LOAD_RELOAD_Msk
#define SysTick_LOAD_RELOAD_Msk (0xFFFFFFUL /*<< SysTick_LOAD_RELOAD_Pos*/)
SysTick LOAD: RELOAD Mask
Definition at line 86 of file perf_counter.c.
SysTick_LOAD_RELOAD_Pos
#define SysTick_LOAD_RELOAD_Pos 0U
SysTick LOAD: RELOAD Position
Definition at line 85 of file perf_counter.c.
SysTick_VAL_CURRENT_Msk
#define SysTick_VAL_CURRENT_Msk (0xFFFFFFUL /*<< SysTick_VAL_CURRENT_Pos*/)
SysTick VAL: CURRENT Mask
Definition at line 90 of file perf_counter.c.
SysTick_VAL_CURRENT_Pos
#define SysTick_VAL_CURRENT_Pos 0U
SysTick VAL: CURRENT Position
Definition at line 89 of file perf_counter.c.
Function Documentation
__on_context_switch_in()
void __on_context_switch_in (uint32_t * pwStack)
Note
if you aren't using perf_counter inside KEIL with RTE, please create ! a header file called `Pre_Include_Global.h`, copy the following ! content into the header file and and put following option ! to your command line (supposing you are using arm compiler 6): ! -include `Pre_Include_Global.h`
update all agents
Definition at line 646 of file perf_counter.c.
{
    struct __task_cycle_info_t *ptRootAgent = (struct __task_cycle_info_t *)pwStack;
    uint64_t dwTimeStamp = get_system_ticks();
    
    ptRootAgent->lLastTimeStamp = dwTimeStamp;
    ptRootAgent->tInfo.hwActiveCount++;
    if (MAGIC_WORD_AGENT_LIST_VALID == ptRootAgent->wMagicWord) {
        task_cycle_info_agent_t *ptAgent = ptRootAgent->tList.ptNext;
        while(NULL != ptAgent) {
            if (NULL != ptAgent->ptInfo) {
                if (ptAgent->ptInfo->bEnabled) {
                    ptAgent->ptInfo->hwActiveCount++;
                }
            }
            ptAgent = ptAgent->ptNext;
        }
    }
}
References task_cycle_info_t::bEnabled, get_system_ticks(), task_cycle_info_t::hwActiveCount, __task_cycle_info_t::lLastTimeStamp, MAGIC_WORD_AGENT_LIST_VALID, task_cycle_info_agent_t::ptInfo, task_cycle_info_agent_t::ptNext, __task_cycle_info_t::tInfo, __task_cycle_info_t::tList, and __task_cycle_info_t::wMagicWord.
Referenced by __freertos_evr_on_task_switched_in(), __on_context_switch(), __rt_thread_scheduler_hook(), and _tx_execution_thread_enter().
__on_context_switch_out()
void __on_context_switch_out (uint32_t * pwStack)
update all agents
Definition at line 668 of file perf_counter.c.
{
    struct __task_cycle_info_t *ptRootAgent = (struct __task_cycle_info_t *)pwStack;
    int64_t lCycleUsed = get_system_ticks() - ptRootAgent->lLastTimeStamp;
    
    ptRootAgent->tInfo.nUsedRecent = lCycleUsed;
    ptRootAgent->tInfo.lUsedTotal += lCycleUsed;
    
    if (MAGIC_WORD_AGENT_LIST_VALID == ptRootAgent->wMagicWord) {
        task_cycle_info_agent_t *ptAgent = ptRootAgent->tList.ptNext;
        while(NULL != ptAgent) {
            if (NULL != ptAgent->ptInfo) {
                if (ptAgent->ptInfo->bEnabled) {
                    ptAgent->ptInfo->nUsedRecent = lCycleUsed;
                    ptAgent->ptInfo->lUsedTotal += lCycleUsed;
                }
            }
            ptAgent = ptAgent->ptNext;
        }
    }
}
References task_cycle_info_t::bEnabled, get_system_ticks(), __task_cycle_info_t::lLastTimeStamp, task_cycle_info_t::lUsedTotal, MAGIC_WORD_AGENT_LIST_VALID, task_cycle_info_t::nUsedRecent, task_cycle_info_agent_t::ptInfo, task_cycle_info_agent_t::ptNext, __task_cycle_info_t::tInfo, __task_cycle_info_t::tList, and __task_cycle_info_t::wMagicWord.
Referenced by __freertos_evr_on_task_switched_out(), __on_context_switch(), __rt_thread_scheduler_hook(), and _tx_execution_thread_exit().
__perf_os_patch_init()
__WEAK void __perf_os_patch_init (void)
Definition at line 248 of file perf_counter.c.
{
}
__start_task_cycle_counter()
void __start_task_cycle_counter (task_cycle_info_t * ptInfo)
Definition at line 691 of file perf_counter.c.
{
    struct __task_cycle_info_t * ptRootAgent =
        (struct __task_cycle_info_t *)get_rtos_task_cycle_info();
    if (NULL == ptRootAgent) {
        return ;
    }
    
    __IRQ_SAFE {
        ptRootAgent->lLastTimeStamp = get_system_ticks();
        ptRootAgent->tInfo.lUsedTotal = 0;
        
        if (NULL != ptInfo) {
            ptInfo->lUsedTotal = 0;
            ptInfo->bEnabled = true;
        }
    }
}
References __IRQ_SAFE, task_cycle_info_t::bEnabled, get_rtos_task_cycle_info(), get_system_ticks(), __task_cycle_info_t::lLastTimeStamp, task_cycle_info_t::lUsedTotal, and __task_cycle_info_t::tInfo.
__stop_task_cycle_counter()
int64_t __stop_task_cycle_counter (task_cycle_info_t * ptInfo)
Definition at line 711 of file perf_counter.c.
{
    struct __task_cycle_info_t * ptRootAgent =
        (struct __task_cycle_info_t *)get_rtos_task_cycle_info();
    if (NULL == ptRootAgent) {
        return 0;
    }
    
    int64_t lCycles = 0;
    
    __IRQ_SAFE {
        int64_t lCycleUsed = get_system_ticks() - ptRootAgent->lLastTimeStamp;
        ptRootAgent->tInfo.lUsedTotal += lCycleUsed;
        if (NULL != ptInfo) {
            if (ptInfo->bEnabled) {
                ptInfo->nUsedRecent = lCycleUsed;
                ptInfo->lUsedTotal += lCycleUsed;
                ptInfo->bEnabled = false;
            }
            
            lCycles = ptInfo->lUsedTotal;
        } else {
            lCycles = ptRootAgent->tInfo.lUsedTotal;
        }
    }
    
    return lCycles;
}
References __IRQ_SAFE, task_cycle_info_t::bEnabled, get_rtos_task_cycle_info(), get_system_ticks(), __task_cycle_info_t::lLastTimeStamp, task_cycle_info_t::lUsedTotal, task_cycle_info_t::nUsedRecent, and __task_cycle_info_t::tInfo.
check_systick()
__STATIC_INLINE int32_t check_systick (void)
Note
this function should only be called when irq is disabled hence SysTick-LOAD and (SCB->ICSR & SCB_ICSR_PENDSTSET_Msk) won't change.
Note
Since we cannot stop counting temporarily, there are several conditions which we should take into consideration:
Condition 1: when assigning nTemp with the register value (LOAD-VAL), the underflow didn't happen but when we check the PENDSTSET bit, the underflow happens, for this condition, we should not do any compensation. When this happens, the (LOAD-nTemp) is
 smaller than PERF_CNT_COMPENSATION_THRESHOLD (a small value) as long as LOAD is bigger than (or equals to) the PERF_CNT_COMPENSATION_THRESHOLD;
Condition 2: when assigning nTemp with the register value (LOAD-VAL), the VAL is zero and underflow happened and the PENDSTSET bit is set, for this condition, we should not do any compensation. When this happens, the (LOAD-nTemp) is equals to zero.
Condition 3: when assigning nTemp with the register value (LOAD-VAL), the underflow has already happened, hence the PENDSTSET is set, for this condition, we should compensate the return value. When this happens, the (LOAD-nTemp) is bigger than (or equals to) PERF_CNT_COMPENSATION_THRESHOLD. The following code implements an equivalent logic.
Definition at line 332 of file perf_counter.c.
{
    int32_t nTemp = (int32_t)SysTick->LOAD - (int32_t)SysTick->VAL;
    if (SCB->ICSR & SCB_ICSR_PENDSTSET_Msk){
        if (((int32_t)SysTick->LOAD - nTemp) >= PERF_CNT_COMPENSATION_THRESHOLD) {
            nTemp += SysTick->LOAD + 1;
        }
    }
    
    return nTemp;
}
References PERF_CNT_COMPENSATION_THRESHOLD, SCB, SCB_ICSR_PENDSTSET_Msk, and SysTick.
Referenced by get_system_ticks(), and stop_cycle_counter().
delay_ms()
void delay_ms (int32_t nMs)
delay specified time in millisecond
Parameters
nUs time in millisecond
Definition at line 417 of file perf_counter.c.
{
    int64_t lUs = nMs * s_nMSUnit;
    
    if (lUs <= PERF_CNT_DELAY_US_COMPENSATION) {
        return ;
    }
    
    lUs -= PERF_CNT_DELAY_US_COMPENSATION;
    
    lUs += get_system_ticks();
    while(get_system_ticks() < lUs);
}
delay_us()
void delay_us (int32_t nUs)
delay specified time in microsecond
Parameters
nUs time in microsecond
Definition at line 398 of file perf_counter.c.
{
    int64_t lUs = nUs * s_nUSUnit;
    
    if (lUs <= PERF_CNT_DELAY_US_COMPENSATION) {
        return ;
    }
    
    lUs -= PERF_CNT_DELAY_US_COMPENSATION;
    
    lUs += get_system_ticks();
    while(get_system_ticks() < lUs);
}
disable_task_cycle_info()
bool disable_task_cycle_info (task_cycle_info_t * ptInfo)
Definition at line 549 of file perf_counter.c.
{
    if (NULL == ptInfo) {
        return false;
    }
    bool bOrig;
    __IRQ_SAFE {
        bOrig = ptInfo->bEnabled;
        ptInfo->bEnabled = false;
    }
    return bOrig;
}
References __IRQ_SAFE, and task_cycle_info_t::bEnabled.
enable_task_cycle_info()
bool enable_task_cycle_info (task_cycle_info_t * ptInfo)
Definition at line 536 of file perf_counter.c.
{
    if (NULL == ptInfo) {
        return false;
    }
    bool bOrig;
    __IRQ_SAFE {
        bOrig = ptInfo->bEnabled;
        ptInfo->bEnabled = true;
    }
    return bOrig;
}
References __IRQ_SAFE, and task_cycle_info_t::bEnabled.
get_rtos_task_cycle_info()
__WEAK task_cycle_info_t * get_rtos_task_cycle_info (void)
Definition at line 501 of file perf_counter.c.
{
    return NULL;
}
Referenced by __start_task_cycle_counter(), __stop_task_cycle_counter(), init_task_cycle_counter(), and register_task_cycle_agent().
get_system_ms()
int32_t get_system_ms (void)
get the elapsed milliseconds since perf_counter is initialised
Returns
int32_t the elapsed milliseconds
Definition at line 488 of file perf_counter.c.
{
    int32_t nTemp = 0;
    
    __IRQ_SAFE {
        nTemp = s_nSystemMS + (check_systick() + s_nMSResidule) / s_nMSUnit;
    }
    
    return nTemp;
}
References __IRQ_SAFE.
get_system_ticks()
int64_t get_system_ticks (void)
get the elapsed cycles since perf_counter is initialised
Returns
int64_t the elpased cycles
Definition at line 472 of file perf_counter.c.
{
    int64_t lTemp = 0;
    
    __IRQ_SAFE {
        lTemp = check_systick() + s_lSystemClockCounts;
    }
    return lTemp;
}
References __IRQ_SAFE, and check_systick().
Referenced by __on_context_switch_in(), __on_context_switch_out(), __start_task_cycle_counter(), __stop_task_cycle_counter(), and init_task_cycle_counter().
init_cycle_counter()
void init_cycle_counter (bool bIsSysTickOccupied)
initialise cycle counter service
Note
- don't forget to tell the function whether the systick is already used by user applications. Don't worry, this cycle counter service won't affect your existing systick service.
- Usually the perf_counter can initialise itself with the help of attribute((constructor(255))), this works fine in Arm Compiler 5 (armcc), Arm Compiler 6 (armclang), arm gcc and llvm. It doesn't work for IAR. So, when you are using IAR, please call this function manually to initialise the perf_counter service.
- Perf_counter library assumes that:
Your project has already using SysTick
It assumes that you have already implemented the SysTick_Handler
It assumes that you have enabled the exception handling for SysTick. If these are not the case, please:
Add an empty SysTick_Handler to your project if you don't have one
Make sure you have the SysTick Exception handling enabled
And call function init_cycle_counter(false) if you doesn't use SysTick in your project at all.
Parameters
bIsSysTickOccupied A boolean value which indicates whether SysTick is already used by user application.
Definition at line 280 of file perf_counter.c.
{
    __IRQ_SAFE {
        if (!bIsSysTickOccupied) {
            SysTick_Config(0x01000000); // use the longest period
        }
        SCB->ICSR = SCB_ICSR_PENDSTCLR_Msk;
    }
    
    start_cycle_counter();
    //s_nSystemClockCounts = s_nCycleCounts;
    s_nOffset = stop_cycle_counter();
    
    s_nUSUnit = SystemCoreClock / 1000000ul;
    s_nMSUnit = SystemCoreClock / 1000ul;
    s_lSystemClockCounts = 0; // reset system cycle counter
    s_nSystemMS = 0; // reset system millisecond counter
    
#if defined(__IS_COMPILER_ARM_COMPILER_5__) \
    || defined(__IS_COMPILER_ARM_COMPILER_6__) \
    || defined(__IS_COMPILER_GCC__) \
    || defined(__IS_COMPILER_LLVM__)
    extern void __ensure_systick_wrapper(void);
    __ensure_systick_wrapper();
#endif
    __perf_os_patch_init();
}
References __IRQ_SAFE, SCB, SCB_ICSR_PENDSTCLR_Msk, start_cycle_counter(), and SysTick_Config().
init_task_cycle_counter()
void init_task_cycle_counter (void)
Definition at line 506 of file perf_counter.c.
{
    struct __task_cycle_info_t * ptRootAgent =
        (struct __task_cycle_info_t *)get_rtos_task_cycle_info();
    if (NULL == ptRootAgent) {
        return ;
    }
    
    memset(ptRootAgent, 0, sizeof(struct __task_cycle_info_t));
    
    ptRootAgent->tList.ptInfo = &(ptRootAgent->tInfo);
    ptRootAgent->tInfo.lStart = get_system_ticks();
    ptRootAgent->wMagicWord = MAGIC_WORD_CANARY;
}
References get_rtos_task_cycle_info(), get_system_ticks(), task_cycle_info_t::lStart, MAGIC_WORD_CANARY, task_cycle_info_agent_t::ptInfo, __task_cycle_info_t::tInfo, __task_cycle_info_t::tList, and __task_cycle_info_t::wMagicWord.
init_task_cycle_info()
task_cycle_info_t * init_task_cycle_info (task_cycle_info_t * ptInfo)
Definition at line 521 of file perf_counter.c.
{
    do {
        if (NULL == ptInfo) {
            break;
        }
        memset(ptInfo, 0, sizeof(task_cycle_info_t));
        ptInfo->bEnabled = true;
    } while(0);
    
    return ptInfo;
}
References task_cycle_info_t::bEnabled.
register_task_cycle_agent()
task_cycle_info_agent_t * register_task_cycle_agent (task_cycle_info_t * ptInfo, task_cycle_info_agent_t * ptAgent)
push to the stack
set next-list
set prev-list
Definition at line 572 of file perf_counter.c.
{
    __IRQ_SAFE {
        do {
            if (NULL == ptAgent || NULL == ptInfo) {
                break;
            }
            
            struct __task_cycle_info_t * ptRootAgent =
                (struct __task_cycle_info_t *)get_rtos_task_cycle_info();
            if (NULL == ptRootAgent) {
                break;
            }
            
            ptRootAgent->wMagicWord = MAGIC_WORD_AGENT_LIST_VALID;
            
            ptAgent->ptInfo = ptInfo;
            
            do {
                ptAgent->ptNext = ptRootAgent->tList.ptNext;
                ptRootAgent->tList.ptNext = ptAgent;
                
                ptAgent->ptPrev = &(ptRootAgent->tList);
                if (NULL != ptAgent->ptNext) {
                    ptAgent->ptNext->ptPrev = ptAgent;
                }
            } while(0);
        
        } while(0);
    }
    
    return ptAgent;
}
References __IRQ_SAFE, get_rtos_task_cycle_info(), MAGIC_WORD_AGENT_LIST_VALID, task_cycle_info_agent_t::ptInfo, task_cycle_info_agent_t::ptNext, task_cycle_info_agent_t::ptPrev, __task_cycle_info_t::tList, and __task_cycle_info_t::wMagicWord.
resume_task_cycle_info()
void resume_task_cycle_info (task_cycle_info_t * ptInfo, bool bEnabledStatus)
Definition at line 562 of file perf_counter.c.
{
    if (NULL == ptInfo) {
        return;
    }
    ptInfo->bEnabled = bEnabledStatus;
}
References task_cycle_info_t::bEnabled.
start_cycle_counter()
bool start_cycle_counter (void)
try to set a start pointer for the performance counter
Return values
false the LOAD register is too small
true performance counter starts
Definition at line 316 of file perf_counter.c.
{
    if (SysTick->LOAD < PERF_CNT_COMPENSATION_THRESHOLD) {
        return false;
    }
    
    __IRQ_SAFE {
        s_nCycleCounts = (int32_t)SysTick->VAL - (int32_t)SysTick->LOAD;
    }
    return true;
}
References __IRQ_SAFE, PERF_CNT_COMPENSATION_THRESHOLD, and SysTick.
Referenced by init_cycle_counter().
stop_cycle_counter()
int32_t stop_cycle_counter (void)
calculate the elapsed cycle count since the last start point
Note
you can have multiple stop_cycle_counter following one start point
Returns
int32_t the elapsed cycle count
Definition at line 372 of file perf_counter.c.
{
    int32_t nTemp = 0;
    __IRQ_SAFE {
        nTemp = check_systick() + s_nCycleCounts;
    }
    return nTemp - s_nOffset;
}
References __IRQ_SAFE, and check_systick().
SysTick_Config()
__STATIC_INLINE uint32_t SysTick_Config (uint32_t ticks)
System Tick Configuration.
Initializes the System Timer and its interrupt, and starts the System Tick Timer. Counter is in free running mode to generate periodic interrupts.
Parameters
 in ticks Number of ticks between two interrupts.
Returns
0 Function succeeded.
1 Function failed.
Note
When the variable __Vendor_SysTickConfig is set to 1, then the function SysTick_Config is not included. In this case, the file device.h must contain a vendor-specific implementation of this function.
Definition at line 200 of file perf_counter.c.
{
    if ((ticks - 1UL) > SysTick_LOAD_RELOAD_Msk)
    {
        return (1UL); /* Reload value impossible */
    }
  
    //__IRQ_SAFE {
        SysTick->CTRL = 0;
        
        SysTick->LOAD = (uint32_t)(ticks - 1UL); /* set reload register */
        //NVIC_SetPriority (SysTick_IRQn, (1UL << __NVIC_PRIO_BITS) - 1UL); /* set Priority for Systick Interrupt */
        SysTick->VAL = 0UL; /* Load the SysTick Counter Value */
        SysTick->CTRL = SysTick_CTRL_CLKSOURCE_Msk |
                           SysTick_CTRL_TICKINT_Msk |
                           SysTick_CTRL_ENABLE_Msk; /* Enable SysTick IRQ and SysTick Timer */
        //SCB->ICSR = SCB_ICSR_PENDSTCLR_Msk;
    //}
    return (0UL); /* Function successful */
}
References SysTick, SysTick_CTRL_CLKSOURCE_Msk, SysTick_CTRL_ENABLE_Msk, SysTick_CTRL_TICKINT_Msk, and SysTick_LOAD_RELOAD_Msk.
Referenced by init_cycle_counter().
unregister_task_cycle_agent()
task_cycle_info_agent_t * unregister_task_cycle_agent (task_cycle_info_agent_t * ptAgent)
already removed
remove agent from the next-list
remove agent from the prev-list
Definition at line 611 of file perf_counter.c.
{
    __IRQ_SAFE {
        do {
            if (NULL == ptAgent) {
                break;
            }
            
            task_cycle_info_agent_t *ptPrev = ptAgent->ptPrev;
            if (NULL == ptPrev) {
                break; /* this should not happen */
            }
            if (ptPrev->ptNext != ptAgent) {
                break;
            }
            
            ptPrev->ptNext = ptAgent->ptNext;
            
            if (NULL != ptAgent->ptNext) {
                ptAgent->ptNext->ptPrev = ptPrev;
            }
            
            ptAgent->ptNext = NULL;
            ptAgent->ptPrev = NULL;
            
        } while(0);
    }
    
    return ptAgent;
}
References __IRQ_SAFE, task_cycle_info_agent_t::ptNext, and task_cycle_info_agent_t::ptPrev.
user_code_insert_to_systick_handler()
void user_code_insert_to_systick_handler (void)
Note
- if you are using a compiler other than armcc or armclang, e.g. iar, arm gcc etc, the systick_wrapper_ual.o doesn't work with the linker of your target toolchain as it use the $Super$$ which is only supported by armlink. For this condition, you have to manually put this function into your existing SysTick_Handler to make the perf_counter library work.
- if you are using Arm Compiler 5 (armcc) or Arm Compiler 6 (armclang) you do NOT have to insert this function into your SysTick_Handler, the systick_wrapper_ual.s will do the work for you.
update system ms counter
Definition at line 233 of file perf_counter.c.
{
    uint32_t wLoad = SysTick->LOAD + 1;
    s_nCycleCounts += wLoad;
    s_lSystemClockCounts += wLoad;
    
    s_nMSResidule += wLoad;
    int32_t nMS = s_nMSResidule / s_nMSUnit;
    s_nMSResidule -= nMS * s_nMSUnit;
    s_nSystemMS += nMS;
}
References SysTick.
Variable Documentation
SystemCoreClock
uint32_t SystemCoreClock [extern]