perf_os_patch_threadx.c File Reference
#include `tx_api.h`
#include `tx_thread.h`
#include `perf_counter.h`
#include `cmsis_compiler.h`
Data Structures
struct __task_cycle_info_t
Macros
#define WRAP_FUNC(__NAME) __WRAP_FUNC(__NAME)
#define ORIG_FUNC(__NAME) __ORIG_FUNC(__NAME)
Functions
void __on_context_switch_in (uint32_t *pwStack)
void __on_context_switch_out (uint32_t *pwStack)
void _tx_execution_thread_enter (void)
void _tx_execution_thread_exit (void)
void _tx_execution_isr_exit (void)
void _tx_execution_isr_enter (void)
task_cycle_info_t * get_rtos_task_cycle_info (void)
Macro Definition Documentation
ORIG_FUNC
#define ORIG_FUNC(__NAME) __ORIG_FUNC(__NAME)
Definition at line 44 of file perf_os_patch_threadx.c.
WRAP_FUNC
#define WRAP_FUNC(__NAME) __WRAP_FUNC(__NAME)
Definition at line 43 of file perf_os_patch_threadx.c.
Function Documentation
__on_context_switch_in()
void __on_context_switch_in (uint32_t * pwStack)
Note
if you aren't using perf_counter inside KEIL with RTE, please create ! a header file called `Pre_Include_Global.h`, copy the following ! content into the header file and and put following option ! to your command line (supposing you are using arm compiler 6): ! -include `Pre_Include_Global.h`
update all agents
Definition at line 646 of file perf_counter.c.
{
    struct __task_cycle_info_t *ptRootAgent = (struct __task_cycle_info_t *)pwStack;
    uint64_t dwTimeStamp = get_system_ticks();
    
    ptRootAgent->lLastTimeStamp = dwTimeStamp;
    ptRootAgent->tInfo.hwActiveCount++;
    if (MAGIC_WORD_AGENT_LIST_VALID == ptRootAgent->wMagicWord) {
        task_cycle_info_agent_t *ptAgent = ptRootAgent->tList.ptNext;
        while(NULL != ptAgent) {
            if (NULL != ptAgent->ptInfo) {
                if (ptAgent->ptInfo->bEnabled) {
                    ptAgent->ptInfo->hwActiveCount++;
                }
            }
            ptAgent = ptAgent->ptNext;
        }
    }
}
References task_cycle_info_t::bEnabled, get_system_ticks(), task_cycle_info_t::hwActiveCount, __task_cycle_info_t::lLastTimeStamp, MAGIC_WORD_AGENT_LIST_VALID, task_cycle_info_agent_t::ptInfo, task_cycle_info_agent_t::ptNext, __task_cycle_info_t::tInfo, __task_cycle_info_t::tList, and __task_cycle_info_t::wMagicWord.
Referenced by _tx_execution_thread_enter().
__on_context_switch_out()
void __on_context_switch_out (uint32_t * pwStack)
update all agents
Definition at line 668 of file perf_counter.c.
{
    struct __task_cycle_info_t *ptRootAgent = (struct __task_cycle_info_t *)pwStack;
    int64_t lCycleUsed = get_system_ticks() - ptRootAgent->lLastTimeStamp;
    
    ptRootAgent->tInfo.nUsedRecent = lCycleUsed;
    ptRootAgent->tInfo.lUsedTotal += lCycleUsed;
    
    if (MAGIC_WORD_AGENT_LIST_VALID == ptRootAgent->wMagicWord) {
        task_cycle_info_agent_t *ptAgent = ptRootAgent->tList.ptNext;
        while(NULL != ptAgent) {
            if (NULL != ptAgent->ptInfo) {
                if (ptAgent->ptInfo->bEnabled) {
                    ptAgent->ptInfo->nUsedRecent = lCycleUsed;
                    ptAgent->ptInfo->lUsedTotal += lCycleUsed;
                }
            }
            ptAgent = ptAgent->ptNext;
        }
    }
}
References task_cycle_info_t::bEnabled, get_system_ticks(), __task_cycle_info_t::lLastTimeStamp, task_cycle_info_t::lUsedTotal, MAGIC_WORD_AGENT_LIST_VALID, task_cycle_info_t::nUsedRecent, task_cycle_info_agent_t::ptInfo, task_cycle_info_agent_t::ptNext, __task_cycle_info_t::tInfo, __task_cycle_info_t::tList, and __task_cycle_info_t::wMagicWord.
Referenced by _tx_execution_thread_exit().
_tx_execution_isr_enter()
void _tx_execution_isr_enter (void)
Definition at line 115 of file perf_os_patch_threadx.c.
{
}
_tx_execution_isr_exit()
void _tx_execution_isr_exit (void)
Definition at line 110 of file perf_os_patch_threadx.c.
{
}
_tx_execution_thread_enter()
void _tx_execution_thread_enter (void)
Definition at line 75 of file perf_os_patch_threadx.c.
{
    TX_THREAD * ptThread = NULL;
    TX_THREAD_GET_CURRENT(ptThread);
    __on_context_switch_in(ptThread->tx_thread_stack_start);
#if defined(TX_EXECUTION_PROFILE_ENABLE)
    extern void ORIG_FUNC(_tx_execution_thread_enter)(void);
    
    ORIG_FUNC(_tx_execution_thread_enter)();
#endif
}
References __on_context_switch_in(), _tx_execution_thread_enter(), and ORIG_FUNC.
Referenced by _tx_execution_thread_enter().
_tx_execution_thread_exit()
void _tx_execution_thread_exit (void)
Definition at line 93 of file perf_os_patch_threadx.c.
{
    TX_THREAD * ptThread = NULL;
    TX_THREAD_GET_CURRENT(ptThread);
    
    if (NULL != ptThread) {
        __on_context_switch_out(ptThread->tx_thread_stack_start);
    }
#if defined(TX_EXECUTION_PROFILE_ENABLE)
    extern void ORIG_FUNC(_tx_execution_thread_exit)(void);
    
    ORIG_FUNC(_tx_execution_thread_exit)();
#endif
}
References __on_context_switch_out(), _tx_execution_thread_exit(), and ORIG_FUNC.
Referenced by _tx_execution_thread_exit().
get_rtos_task_cycle_info()
task_cycle_info_t * get_rtos_task_cycle_info (void)
Definition at line 121 of file perf_os_patch_threadx.c.
{
    TX_THREAD * ptThread = NULL;
    TX_THREAD_GET_CURRENT(ptThread);
    return &(((struct __task_cycle_info_t *)ptThread->tx_thread_stack_start)->tInfo);
}