perf_os_patch_rtx5.c File Reference
#include `rtx_os.h`
#include `perf_counter.h`
#include `cmsis_compiler.h`
#include `rtx_evr.h`
Data Structures
struct __task_cycle_info_t
Macros
#define WRAP_FUNC(__NAME) __WRAP_FUNC(__NAME)
#define ORIG_FUNC(__NAME) __ORIG_FUNC(__NAME)
Functions
void __on_context_switch_in (uint32_t *pwStack)
void __on_context_switch_out (uint32_t *pwStack)
void __on_context_switch (osRtxThread_t *thread)
wrapper function for rtos context switching
task_cycle_info_t * get_rtos_task_cycle_info (void)
Macro Definition Documentation
ORIG_FUNC
#define ORIG_FUNC(__NAME) __ORIG_FUNC(__NAME)
Definition at line 44 of file perf_os_patch_rtx5.c.
WRAP_FUNC
#define WRAP_FUNC(__NAME) __WRAP_FUNC(__NAME)
Definition at line 43 of file perf_os_patch_rtx5.c.
Function Documentation
__on_context_switch()
void __on_context_switch (osRtxThread_t * thread)
wrapper function for rtos context switching
Definition at line 65 of file perf_os_patch_rtx5.c.
{
    if (NULL != osRtxInfo.thread.run.curr) {
        __on_context_switch_out(osRtxInfo.thread.run.curr->stack_mem);
    }
    
    __on_context_switch_in(thread->stack_mem);
}
References __on_context_switch_in(), and __on_context_switch_out().
__on_context_switch_in()
void __on_context_switch_in (uint32_t * pwStack)
Note
if you aren't using perf_counter inside KEIL with RTE, please create ! a header file called `Pre_Include_Global.h`, copy the following ! content into the header file and and put following option ! to your command line (supposing you are using arm compiler 6): ! -include `Pre_Include_Global.h`
update all agents
Definition at line 646 of file perf_counter.c.
{
    struct __task_cycle_info_t *ptRootAgent = (struct __task_cycle_info_t *)pwStack;
    uint64_t dwTimeStamp = get_system_ticks();
    
    ptRootAgent->lLastTimeStamp = dwTimeStamp;
    ptRootAgent->tInfo.hwActiveCount++;
    if (MAGIC_WORD_AGENT_LIST_VALID == ptRootAgent->wMagicWord) {
        task_cycle_info_agent_t *ptAgent = ptRootAgent->tList.ptNext;
        while(NULL != ptAgent) {
            if (NULL != ptAgent->ptInfo) {
                if (ptAgent->ptInfo->bEnabled) {
                    ptAgent->ptInfo->hwActiveCount++;
                }
            }
            ptAgent = ptAgent->ptNext;
        }
    }
}
Referenced by __on_context_switch().
__on_context_switch_out()
void __on_context_switch_out (uint32_t * pwStack)
update all agents
Definition at line 668 of file perf_counter.c.
{
    struct __task_cycle_info_t *ptRootAgent = (struct __task_cycle_info_t *)pwStack;
    int64_t lCycleUsed = get_system_ticks() - ptRootAgent->lLastTimeStamp;
    
    ptRootAgent->tInfo.nUsedRecent = lCycleUsed;
    ptRootAgent->tInfo.lUsedTotal += lCycleUsed;
    
    if (MAGIC_WORD_AGENT_LIST_VALID == ptRootAgent->wMagicWord) {
        task_cycle_info_agent_t *ptAgent = ptRootAgent->tList.ptNext;
        while(NULL != ptAgent) {
            if (NULL != ptAgent->ptInfo) {
                if (ptAgent->ptInfo->bEnabled) {
                    ptAgent->ptInfo->nUsedRecent = lCycleUsed;
                    ptAgent->ptInfo->lUsedTotal += lCycleUsed;
                }
            }
            ptAgent = ptAgent->ptNext;
        }
    }
}
Referenced by __on_context_switch().
get_rtos_task_cycle_info()
task_cycle_info_t * get_rtos_task_cycle_info (void)
Definition at line 90 of file perf_os_patch_rtx5.c.
{
    osRtxThread_t *curr = osRtxInfo.thread.run.curr;
    if (NULL == curr) {
        return NULL;
    }
    
    return &(((struct __task_cycle_info_t *)curr->stack_mem)->tInfo);
}