perf_os_patch_rt_thread.c File Reference
#include <rtthread.h>
#include `perf_counter.h`
#include `cmsis_compiler.h`
Data Structures
struct __task_cycle_info_t
Macros
#define WRAP_FUNC(__NAME) __WRAP_FUNC(__NAME)
#define ORIG_FUNC(__NAME) __ORIG_FUNC(__NAME)
Functions
void __on_context_switch_in (uint32_t *pwStack)
void __on_context_switch_out (uint32_t *pwStack)
void __rt_thread_scheduler_hook (struct rt_thread *from, struct rt_thread *to)
void __perf_os_patch_init (void)
task_cycle_info_t * get_rtos_task_cycle_info (void)
Variables
struct rt_thread * rt_current_thread
Macro Definition Documentation
ORIG_FUNC
#define ORIG_FUNC(__NAME) __ORIG_FUNC(__NAME)
Definition at line 43 of file perf_os_patch_rt_thread.c.
WRAP_FUNC
#define WRAP_FUNC(__NAME) __WRAP_FUNC(__NAME)
Definition at line 42 of file perf_os_patch_rt_thread.c.
Function Documentation
__on_context_switch_in()
void __on_context_switch_in (uint32_t * pwStack)
Note
if you aren't using perf_counter inside KEIL with RTE, please create ! a header file called `Pre_Include_Global.h`, copy the following ! content into the header file and and put following option ! to your command line (supposing you are using arm compiler 6): ! -include `Pre_Include_Global.h`
update all agents
Definition at line 646 of file perf_counter.c.
{
    struct __task_cycle_info_t *ptRootAgent = (struct __task_cycle_info_t *)pwStack;
    uint64_t dwTimeStamp = get_system_ticks();
    
    ptRootAgent->lLastTimeStamp = dwTimeStamp;
    ptRootAgent->tInfo.hwActiveCount++;
    if (MAGIC_WORD_AGENT_LIST_VALID == ptRootAgent->wMagicWord) {
        task_cycle_info_agent_t *ptAgent = ptRootAgent->tList.ptNext;
        while(NULL != ptAgent) {
            if (NULL != ptAgent->ptInfo) {
                if (ptAgent->ptInfo->bEnabled) {
                    ptAgent->ptInfo->hwActiveCount++;
                }
            }
            ptAgent = ptAgent->ptNext;
        }
    }
}
Referenced by __rt_thread_scheduler_hook().
__on_context_switch_out()
void __on_context_switch_out (uint32_t * pwStack)
update all agents
Definition at line 668 of file perf_counter.c.
{
    struct __task_cycle_info_t *ptRootAgent = (struct __task_cycle_info_t *)pwStack;
    int64_t lCycleUsed = get_system_ticks() - ptRootAgent->lLastTimeStamp;
    
    ptRootAgent->tInfo.nUsedRecent = lCycleUsed;
    ptRootAgent->tInfo.lUsedTotal += lCycleUsed;
    
    if (MAGIC_WORD_AGENT_LIST_VALID == ptRootAgent->wMagicWord) {
        task_cycle_info_agent_t *ptAgent = ptRootAgent->tList.ptNext;
        while(NULL != ptAgent) {
            if (NULL != ptAgent->ptInfo) {
                if (ptAgent->ptInfo->bEnabled) {
                    ptAgent->ptInfo->nUsedRecent = lCycleUsed;
                    ptAgent->ptInfo->lUsedTotal += lCycleUsed;
                }
            }
            ptAgent = ptAgent->ptNext;
        }
    }
}
Referenced by __rt_thread_scheduler_hook().
__perf_os_patch_init()
void __perf_os_patch_init (void)
Definition at line 79 of file perf_os_patch_rt_thread.c.
{
    rt_scheduler_sethook(&__rt_thread_scheduler_hook);
}
References __rt_thread_scheduler_hook().
__rt_thread_scheduler_hook()
void __rt_thread_scheduler_hook (struct rt_thread * from, struct rt_thread * to)
Definition at line 69 of file perf_os_patch_rt_thread.c.
{
    if (NULL != from) {
        __on_context_switch_out(from->stack_addr);
    }
    
    __on_context_switch_in(to->stack_addr);
}
References __on_context_switch_in(), and __on_context_switch_out().
Referenced by __perf_os_patch_init().
get_rtos_task_cycle_info()
task_cycle_info_t * get_rtos_task_cycle_info (void)
Definition at line 85 of file perf_os_patch_rt_thread.c.
{
    return &(((struct __task_cycle_info_t *)rt_current_thread->stack_addr)->tInfo);
}
References rt_current_thread.
Variable Documentation
rt_current_thread
struct rt_thread* rt_current_thread [extern]
Referenced by get_rtos_task_cycle_info().