perf_counter.h File Reference
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include `cmsis_compiler.h`
Data Structures
struct task_cycle_info_t
struct task_cycle_info_agent_t
Macros
#define __PERF_COUNTER_VER_MAJOR__ 1
#define __PERF_COUNTER_VER_MINOR__ 9
#define __PERF_COUNTER_VER_REVISE__ 5
#define __PERF_COUNTER_VER_STR__ `dev`
#define __PER_COUNTER_VER__
#define __PLOOC_VA_NUM_ARGS_IMPL(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, __N, ...) __N
#define __PLOOC_VA_NUM_ARGS(...)
#define UNUSED_PARAM(__VAR) (void)(__VAR)
#define __MACRO_EXPANDING(...) __VA_ARGS__
#define __CONNECT2(__A, __B) __A##__B
#define __CONNECT3(__A, __B, __C) __A##__B##__C
#define __CONNECT4(__A, __B, __C, __D) __A##__B##__C##__D
#define __CONNECT5(__A, __B, __C, __D, __E) __A##__B##__C##__D##__E
#define __CONNECT6(__A, __B, __C, __D, __E, __F) __A##__B##__C##__D##__E##__F
#define __CONNECT7(__A, __B, __C, __D, __E, __F, __G) __A##__B##__C##__D##__E##__F##__G
#define __CONNECT8(__A, __B, __C, __D, __E, __F, __G, __H) __A##__B##__C##__D##__E##__F##__G##__H
#define __CONNECT9(__A, __B, __C, __D, __E, __F, __G, __H, __I) __A##__B##__C##__D##__E##__F##__G##__H##__I
#define ALT_CONNECT2(__A, __B) __CONNECT2(__A, __B)
#define CONNECT2(__A, __B) __CONNECT2(__A, __B)
#define CONNECT3(__A, __B, __C) __CONNECT3(__A, __B, __C)
#define CONNECT4(__A, __B, __C, __D) __CONNECT4(__A, __B, __C, __D)
#define CONNECT5(__A, __B, __C, __D, __E) __CONNECT5(__A, __B, __C, __D, __E)
#define CONNECT6(__A, __B, __C, __D, __E, __F) __CONNECT6(__A, __B, __C, __D, __E, __F)
#define CONNECT7(__A, __B, __C, __D, __E, __F, __G) __CONNECT7(__A, __B, __C, __D, __E, __F, __G)
#define CONNECT8(__A, __B, __C, __D, __E, __F, __G, __H) __CONNECT8(__A, __B, __C, __D, __E, __F, __G, __H)
#define CONNECT9(__A, __B, __C, __D, __E, __F, __G, __H, __I) __CONNECT9(__A, __B, __C, __D, __E, __F, __G, __H, __I)
#define CONNECT(...) ALT_CONNECT2(CONNECT, __PLOOC_VA_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)
#define __using1(__declare)
#define __using2(__declare, __on_leave_expr)
#define __using3(__declare, __on_enter_expr, __on_leave_expr)
#define __using4(__dcl1, __dcl2, __on_enter_expr, __on_leave_expr)
#define using(...) CONNECT2(__using, __PLOOC_VA_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)
#define __with2(__type, __addr) using(__type *_=(__addr))
#define __with3(__type, __addr, __item) using(__type *_=(__addr), *__item = _, _=_,_=_)
#define with(...) CONNECT2(__with, __PLOOC_VA_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)
#define dimof(__array) (sizeof(__array)/sizeof(__array[0]))
#define SAFE_NAME(__NAME) CONNECT3(__,__NAME,__LINE__)
#define foreach2(__type, __array)
#define foreach3(__type, __array, __item)
#define foreach(...) CONNECT2(foreach, __PLOOC_VA_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)
#define safe_atom_code()
#define __IRQ_SAFE
#define __cycleof__(__STR, ...)
#define __super_loop_monitor__(__N, ...)
#define start_task_cycle_counter(...) start_cycle_counter()
#define stop_task_cycle_counter(...) stop_cycle_counter()
#define init_task_cycle_counter()
#define register_task_cycle_agent(...)
#define unregister_task_cycle_agent(...)
#define init_task_cycle_info(...) (NULL)
#define enable_task_cycle_info(...) (false)
#define disable_task_cycle_info(...) (false)
#define resume_task_cycle_info(...)
Typedefs
typedef struct task_cycle_info_agent_t task_cycle_info_agent_t
Functions
bool start_cycle_counter (void)
try to set a start pointer for the performance counter
int32_t stop_cycle_counter (void)
calculate the elapsed cycle count since the last start point
void delay_us (int32_t nUs)
delay specified time in microsecond
void delay_ms (int32_t nMs)
delay specified time in millisecond
int64_t get_system_ticks (void)
get the elapsed cycles since perf_counter is initialised
int32_t get_system_ms (void)
get the elapsed milliseconds since perf_counter is initialised
void init_cycle_counter (bool bIsSysTickOccupied)
initialise cycle counter service
void user_code_insert_to_systick_handler (void)
Macro Definition Documentation
__CONNECT2
#define __CONNECT2(__A, __B) __A##__B
Definition at line 148 of file perf_counter.h.
__CONNECT3
#define __CONNECT3(__A, __B, __C) __A##__B##__C
Definition at line 149 of file perf_counter.h.
__CONNECT4
#define __CONNECT4(__A, __B, __C, __D) __A##__B##__C##__D
Definition at line 150 of file perf_counter.h.
__CONNECT5
#define __CONNECT5(__A, __B, __C, __D, __E) __A##__B##__C##__D##__E
Definition at line 151 of file perf_counter.h.
__CONNECT6
#define __CONNECT6(__A, __B, __C, __D, __E, __F) __A##__B##__C##__D##__E##__F
Definition at line 152 of file perf_counter.h.
__CONNECT7
#define __CONNECT7(__A, __B, __C, __D, __E, __F, __G) __A##__B##__C##__D##__E##__F##__G
Definition at line 153 of file perf_counter.h.
__CONNECT8
#define __CONNECT8(__A, __B, __C, __D, __E, __F, __G, __H) __A##__B##__C##__D##__E##__F##__G##__H
Definition at line 155 of file perf_counter.h.
__CONNECT9
#define __CONNECT9(__A, __B, __C, __D, __E, __F, __G, __H, __I) __A##__B##__C##__D##__E##__F##__G##__H##__I
Definition at line 157 of file perf_counter.h.
__cycleof__
#define __cycleof__(__STR, ...)
Value:
            using(int64_t _ = get_system_ticks(), __cycle_count__ = _, \
                _=_, { \
                _ = get_system_ticks() - _; \
                __cycle_count__ = _; \
                if (__PLOOC_VA_NUM_ARGS(__VA_ARGS__) == 0) { \
                    printf("\r\n"); \
                    printf("-[Cycle Report]"); \
                    printf("--------------------------------------------\r\n"); \
                    printf(__STR " total cycle count: %d [%08x]\r\n", \
                            (int)_, (int)_); \
                } else { \
                    __VA_ARGS__ \
                }; \
            })
Definition at line 280 of file perf_counter.h.
__IRQ_SAFE
#define __IRQ_SAFE
Value:
            using(uint32_t SAFE_NAME(temp) = \
                        ({ uint32_t SAFE_NAME(temp2)=__get_PRIMASK(); \
                            __disable_irq(); \
                            SAFE_NAME(temp2);}), \
                        __set_PRIMASK(SAFE_NAME(temp)))
Definition at line 264 of file perf_counter.h.
__MACRO_EXPANDING
#define __MACRO_EXPANDING(...) __VA_ARGS__
Definition at line 146 of file perf_counter.h.
__PER_COUNTER_VER__
#define __PER_COUNTER_VER__
Value:
                               (__PERF_COUNTER_VER_MAJOR__ * 10000ul \
                               +__PERF_COUNTER_VER_MINOR__ * 100ul \
                               +__PERF_COUNTER_VER_REVISE__)
Definition at line 38 of file perf_counter.h.
__PERF_COUNTER_VER_MAJOR__
#define __PERF_COUNTER_VER_MAJOR__ 1
Definition at line 32 of file perf_counter.h.
__PERF_COUNTER_VER_MINOR__
#define __PERF_COUNTER_VER_MINOR__ 9
Definition at line 33 of file perf_counter.h.
__PERF_COUNTER_VER_REVISE__
#define __PERF_COUNTER_VER_REVISE__ 5
Definition at line 34 of file perf_counter.h.
__PERF_COUNTER_VER_STR__
#define __PERF_COUNTER_VER_STR__ `dev`
Definition at line 36 of file perf_counter.h.
__PLOOC_VA_NUM_ARGS
#define __PLOOC_VA_NUM_ARGS(...)
Value:
            __PLOOC_VA_NUM_ARGS_IMPL(0,##__VA_ARGS__,16,15,14,13,12,11,10,9, \
                                      8,7,6,5,4,3,2,1,0)
Definition at line 116 of file perf_counter.h.
__PLOOC_VA_NUM_ARGS_IMPL
#define __PLOOC_VA_NUM_ARGS_IMPL(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, __N, ...) __N
Note
for IAR
for arm compiler 5
for arm compiler 6
for gcc
Definition at line 111 of file perf_counter.h.
__super_loop_monitor__
#define __super_loop_monitor__(__N, ...)
Value:
    using(\
        struct { \
            int64_t lStart; \
            int64_t lTaskUsedCycles; \
            int64_t lTimeElapsed; \
        } __cpu_usage__ = {.lStart = get_system_ticks()}) \
    using(int SAFE_NAME(cnt) = (__N)) \
    for(start_task_cycle_counter();; ({ \
        if (!(--SAFE_NAME(cnt))) { \
            __cpu_usage__.lTimeElapsed \
                = get_system_ticks() - __cpu_usage__.lStart; \
            __cpu_usage__.lTaskUsedCycles = stop_task_cycle_counter(); \
                                                                                \
            if (__PLOOC_VA_NUM_ARGS(__VA_ARGS__) == 0) { \
                printf("%s CPU Usage %2.3f%%\r\n", __func__, \
                        (float)((double)__cpu_usage__.lTaskUsedCycles * 100.0 / \
                                (double)__cpu_usage__.lTimeElapsed)); \
            } else { \
                __VA_ARGS__; \
            } \
            SAFE_NAME(cnt) = (__N); \
            __cpu_usage__.lStart = get_system_ticks(); \
            start_task_cycle_counter(); \
        }; \
    }))
Definition at line 298 of file perf_counter.h.
__using1
#define __using1(__declare)
Value:
            for (__declare, *CONNECT3(__using_, __LINE__,_ptr) = NULL; \
                 CONNECT3(__using_, __LINE__,_ptr)++ == NULL; \
                )
Definition at line 183 of file perf_counter.h.
__using2
#define __using2(__declare, __on_leave_expr)
Value:
            for (__declare, *CONNECT3(__using_, __LINE__,_ptr) = NULL; \
                 CONNECT3(__using_, __LINE__,_ptr)++ == NULL; \
                 (__on_leave_expr) \
                )
Definition at line 188 of file perf_counter.h.
__using3
#define __using3(__declare, __on_enter_expr, __on_leave_expr)
Value:
            for (__declare, *CONNECT3(__using_, __LINE__,_ptr) = NULL; \
                 CONNECT3(__using_, __LINE__,_ptr)++ == NULL ? \
                    ((__on_enter_expr),1) : 0; \
                 (__on_leave_expr) \
                )
Definition at line 194 of file perf_counter.h.
__using4
#define __using4(__dcl1, __dcl2, __on_enter_expr, __on_leave_expr)
Value:
            for (__dcl1, __dcl2, *CONNECT3(__using_, __LINE__,_ptr) = NULL; \
                 CONNECT3(__using_, __LINE__,_ptr)++ == NULL ? \
                    ((__on_enter_expr),1) : 0; \
                 (__on_leave_expr) \
                )
Definition at line 201 of file perf_counter.h.
__with2
#define __with2(__type, __addr) using(__type *_=(__addr))
Definition at line 216 of file perf_counter.h.
__with3
#define __with3(__type, __addr, __item) using(__type *_=(__addr), *__item = _, _=_,_=_)
Definition at line 218 of file perf_counter.h.
ALT_CONNECT2
#define ALT_CONNECT2(__A, __B) __CONNECT2(__A, __B)
Definition at line 160 of file perf_counter.h.
CONNECT
#define CONNECT(...) ALT_CONNECT2(CONNECT, __PLOOC_VA_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)
Definition at line 174 of file perf_counter.h.
CONNECT2
#define CONNECT2(__A, __B) __CONNECT2(__A, __B)
Definition at line 161 of file perf_counter.h.
CONNECT3
#define CONNECT3(__A, __B, __C) __CONNECT3(__A, __B, __C)
Definition at line 162 of file perf_counter.h.
CONNECT4
#define CONNECT4(__A, __B, __C, __D) __CONNECT4(__A, __B, __C, __D)
Definition at line 163 of file perf_counter.h.
CONNECT5
#define CONNECT5(__A, __B, __C, __D, __E) __CONNECT5(__A, __B, __C, __D, __E)
Definition at line 164 of file perf_counter.h.
CONNECT6
#define CONNECT6(__A, __B, __C, __D, __E, __F) __CONNECT6(__A, __B, __C, __D, __E, __F)
Definition at line 165 of file perf_counter.h.
CONNECT7
#define CONNECT7(__A, __B, __C, __D, __E, __F, __G) __CONNECT7(__A, __B, __C, __D, __E, __F, __G)
Definition at line 167 of file perf_counter.h.
CONNECT8
#define CONNECT8(__A, __B, __C, __D, __E, __F, __G, __H) __CONNECT8(__A, __B, __C, __D, __E, __F, __G, __H)
Definition at line 169 of file perf_counter.h.
CONNECT9
#define CONNECT9(__A, __B, __C, __D, __E, __F, __G, __H, __I) __CONNECT9(__A, __B, __C, __D, __E, __F, __G, __H, __I)
Definition at line 171 of file perf_counter.h.
dimof
#define dimof(__array) (sizeof(__array)/sizeof(__array[0]))
Definition at line 227 of file perf_counter.h.
disable_task_cycle_info
#define disable_task_cycle_info(...) (false)
Definition at line 531 of file perf_counter.h.
enable_task_cycle_info
#define enable_task_cycle_info(...) (false)
Definition at line 530 of file perf_counter.h.
foreach
#define foreach(...) CONNECT2(foreach, __PLOOC_VA_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)
Definition at line 251 of file perf_counter.h.
foreach2
#define foreach2(__type, __array)
Value:
            using(__type *_ = __array) \
            for (uint_fast32_t SAFE_NAME(count) = dimof(__array); \
                    SAFE_NAME(count) > 0; \
                    _++, SAFE_NAME(count)-- \
                )
Definition at line 237 of file perf_counter.h.
foreach3
#define foreach3(__type, __array, __item)
Value:
            using(__type *_ = __array, *__item = _, _ = _, _ = _) \
            for (uint_fast32_t SAFE_NAME(count) = dimof(__array); \
                    SAFE_NAME(count) > 0; \
                    _++, __item = _, SAFE_NAME(count)-- \
                )
Definition at line 244 of file perf_counter.h.
init_task_cycle_counter
#define init_task_cycle_counter(void)
Definition at line 526 of file perf_counter.h.
init_task_cycle_info
#define init_task_cycle_info(...) (NULL)
Definition at line 529 of file perf_counter.h.
register_task_cycle_agent
#define register_task_cycle_agent(...)
Definition at line 527 of file perf_counter.h.
resume_task_cycle_info
#define resume_task_cycle_info(...)
Definition at line 532 of file perf_counter.h.
safe_atom_code
#define safe_atom_code()
Value:
            using(uint32_t SAFE_NAME(temp) = \
                        ({ uint32_t SAFE_NAME(temp2)=__get_PRIMASK(); \
                            __disable_irq(); \
                            SAFE_NAME(temp2);}), \
                        __set_PRIMASK(SAFE_NAME(temp)))
Definition at line 255 of file perf_counter.h.
SAFE_NAME
#define SAFE_NAME(__NAME) CONNECT3(__,__NAME,__LINE__)
Definition at line 231 of file perf_counter.h.
start_task_cycle_counter
#define start_task_cycle_counter(...) start_cycle_counter()
Definition at line 524 of file perf_counter.h.
stop_task_cycle_counter
#define stop_task_cycle_counter(...) stop_cycle_counter()
Definition at line 525 of file perf_counter.h.
unregister_task_cycle_agent
#define unregister_task_cycle_agent(...)
Definition at line 528 of file perf_counter.h.
UNUSED_PARAM
#define UNUSED_PARAM(__VAR) (void)(__VAR)
Definition at line 122 of file perf_counter.h.
using
#define using(...) CONNECT2(__using, __PLOOC_VA_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)
Definition at line 208 of file perf_counter.h.
with
#define with(...) CONNECT2(__with, __PLOOC_VA_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)
Definition at line 221 of file perf_counter.h.
Typedef Documentation
task_cycle_info_agent_t
typedef struct task_cycle_info_agent_t task_cycle_info_agent_t
Definition at line 335 of file perf_counter.h.
Function Documentation
delay_ms()
void delay_ms (int32_t nMs)
delay specified time in millisecond
Parameters
nUs time in millisecond
Definition at line 417 of file perf_counter.c.
{
    int64_t lUs = nMs * s_nMSUnit;
    
    if (lUs <= PERF_CNT_DELAY_US_COMPENSATION) {
        return ;
    }
    
    lUs -= PERF_CNT_DELAY_US_COMPENSATION;
    
    lUs += get_system_ticks();
    while(get_system_ticks() < lUs);
}
delay_us()
void delay_us (int32_t nUs)
delay specified time in microsecond
Parameters
nUs time in microsecond
Definition at line 398 of file perf_counter.c.
{
    int64_t lUs = nUs * s_nUSUnit;
    
    if (lUs <= PERF_CNT_DELAY_US_COMPENSATION) {
        return ;
    }
    
    lUs -= PERF_CNT_DELAY_US_COMPENSATION;
    
    lUs += get_system_ticks();
    while(get_system_ticks() < lUs);
}
get_system_ms()
int32_t get_system_ms (void)
get the elapsed milliseconds since perf_counter is initialised
Returns
int32_t the elapsed milliseconds
Definition at line 488 of file perf_counter.c.
{
    int32_t nTemp = 0;
    
    __IRQ_SAFE {
        nTemp = s_nSystemMS + (check_systick() + s_nMSResidule) / s_nMSUnit;
    }
    
    return nTemp;
}
References __IRQ_SAFE.
get_system_ticks()
int64_t get_system_ticks (void)
get the elapsed cycles since perf_counter is initialised
Returns
int64_t the elpased cycles
Definition at line 472 of file perf_counter.c.
{
    int64_t lTemp = 0;
    
    __IRQ_SAFE {
        lTemp = check_systick() + s_lSystemClockCounts;
    }
    return lTemp;
}
References __IRQ_SAFE, and check_systick().
Referenced by __on_context_switch_in(), __on_context_switch_out(), __start_task_cycle_counter(), __stop_task_cycle_counter(), and init_task_cycle_counter().
init_cycle_counter()
void init_cycle_counter (bool bIsSysTickOccupied)
initialise cycle counter service
Note
- don't forget to tell the function whether the systick is already used by user applications. Don't worry, this cycle counter service won't affect your existing systick service.
- Usually the perf_counter can initialise itself with the help of attribute((constructor(255))), this works fine in Arm Compiler 5 (armcc), Arm Compiler 6 (armclang), arm gcc and llvm. It doesn't work for IAR. So, when you are using IAR, please call this function manually to initialise the perf_counter service.
- Perf_counter library assumes that:
Your project has already using SysTick
It assumes that you have already implemented the SysTick_Handler
It assumes that you have enabled the exception handling for SysTick. If these are not the case, please:
Add an empty SysTick_Handler to your project if you don't have one
Make sure you have the SysTick Exception handling enabled
And call function init_cycle_counter(false) if you doesn't use SysTick in your project at all.
Parameters
bIsSysTickOccupied A boolean value which indicates whether SysTick is already used by user application.
Definition at line 280 of file perf_counter.c.
{
    __IRQ_SAFE {
        if (!bIsSysTickOccupied) {
            SysTick_Config(0x01000000); // use the longest period
        }
        SCB->ICSR = SCB_ICSR_PENDSTCLR_Msk;
    }
    
    start_cycle_counter();
    //s_nSystemClockCounts = s_nCycleCounts;
    s_nOffset = stop_cycle_counter();
    
    s_nUSUnit = SystemCoreClock / 1000000ul;
    s_nMSUnit = SystemCoreClock / 1000ul;
    s_lSystemClockCounts = 0; // reset system cycle counter
    s_nSystemMS = 0; // reset system millisecond counter
    
#if defined(__IS_COMPILER_ARM_COMPILER_5__) \
    || defined(__IS_COMPILER_ARM_COMPILER_6__) \
    || defined(__IS_COMPILER_GCC__) \
    || defined(__IS_COMPILER_LLVM__)
    extern void __ensure_systick_wrapper(void);
    __ensure_systick_wrapper();
#endif
    __perf_os_patch_init();
}
References __IRQ_SAFE, SCB, SCB_ICSR_PENDSTCLR_Msk, start_cycle_counter(), and SysTick_Config().
start_cycle_counter()
bool start_cycle_counter (void)
try to set a start pointer for the performance counter
Return values
false the LOAD register is too small
true performance counter starts
Definition at line 316 of file perf_counter.c.
{
    if (SysTick->LOAD < PERF_CNT_COMPENSATION_THRESHOLD) {
        return false;
    }
    
    __IRQ_SAFE {
        s_nCycleCounts = (int32_t)SysTick->VAL - (int32_t)SysTick->LOAD;
    }
    return true;
}
References __IRQ_SAFE, PERF_CNT_COMPENSATION_THRESHOLD, and SysTick.
Referenced by init_cycle_counter().
stop_cycle_counter()
int32_t stop_cycle_counter (void)
calculate the elapsed cycle count since the last start point
Note
you can have multiple stop_cycle_counter following one start point
Returns
int32_t the elapsed cycle count
Definition at line 372 of file perf_counter.c.
{
    int32_t nTemp = 0;
    __IRQ_SAFE {
        nTemp = check_systick() + s_nCycleCounts;
    }
    return nTemp - s_nOffset;
}
References __IRQ_SAFE, and check_systick().
user_code_insert_to_systick_handler()
void user_code_insert_to_systick_handler (void)
Note
- if you are using a compiler other than armcc or armclang, e.g. iar, arm gcc etc, the systick_wrapper_ual.o doesn't work with the linker of your target toolchain as it use the $Super$$ which is only supported by armlink. For this condition, you have to manually put this function into your existing SysTick_Handler to make the perf_counter library work.
- if you are using Arm Compiler 5 (armcc) or Arm Compiler 6 (armclang) you do NOT have to insert this function into your SysTick_Handler, the systick_wrapper_ual.s will do the work for you.
update system ms counter
Definition at line 233 of file perf_counter.c.
{
    uint32_t wLoad = SysTick->LOAD + 1;
    s_nCycleCounts += wLoad;
    s_lSystemClockCounts += wLoad;
    
    s_nMSResidule += wLoad;
    int32_t nMS = s_nMSResidule / s_nMSUnit;
    s_nMSResidule -= nMS * s_nMSUnit;
    s_nSystemMS += nMS;
}
References SysTick.