perf_os_patch_freertos.c File Reference
#include `FreeRTOS.h`
#include `task.h`
#include `timers.h`
#include `stack_macros.h`
#include `perf_counter.h`
#include `cmsis_compiler.h`
Data Structures
struct __task_cycle_info_t
struct tskTaskControlBlock
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define WRAP_FUNC(__NAME) __WRAP_FUNC(__NAME)
#define ORIG_FUNC(__NAME) __ORIG_FUNC(__NAME)
#define EvtFreeRTOSTasksNo (0xF0U)
#define EvtFreeRTOSTasks_TaskSwitchedOut EventID(EventLevelOp, EvtFreeRTOSTasksNo, 0x0BU)
#define EvtFreeRTOSTasks_TaskSwitchedIn EventID(EventLevelOp, EvtFreeRTOSTasksNo, 0x0CU)
Typedefs
typedef struct tskTaskControlBlock tskTCB
typedef tskTCB TCB_t
Functions
void __on_context_switch_in (uint32_t *pwStack)
void __on_context_switch_out (uint32_t *pwStack)
void __freertos_evr_on_task_switched_out (void *ptTCB)
void __freertos_evr_on_task_switched_in (void *ptTCB, uint32_t uxTopPriority)
task_cycle_info_t * get_rtos_task_cycle_info (void)
Variables
PRIVILEGED_DATA TCB_t *volatile pxCurrentTCB
Macro Definition Documentation
EvtFreeRTOSTasks_TaskSwitchedIn
#define EvtFreeRTOSTasks_TaskSwitchedIn EventID(EventLevelOp, EvtFreeRTOSTasksNo, 0x0CU)
Definition at line 210 of file perf_os_patch_freertos.c.
EvtFreeRTOSTasks_TaskSwitchedOut
#define EvtFreeRTOSTasks_TaskSwitchedOut EventID(EventLevelOp, EvtFreeRTOSTasksNo, 0x0BU)
Definition at line 208 of file perf_os_patch_freertos.c.
EvtFreeRTOSTasksNo
#define EvtFreeRTOSTasksNo (0xF0U)
Definition at line 206 of file perf_os_patch_freertos.c.
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 25 of file perf_os_patch_freertos.c.
ORIG_FUNC
#define ORIG_FUNC(__NAME) __ORIG_FUNC(__NAME)
Definition at line 59 of file perf_os_patch_freertos.c.
WRAP_FUNC
#define WRAP_FUNC(__NAME) __WRAP_FUNC(__NAME)
Definition at line 58 of file perf_os_patch_freertos.c.
Typedef Documentation
TCB_t
typedef tskTCB TCB_t
Definition at line 158 of file perf_os_patch_freertos.c.
tskTCB
typedef struct tskTaskControlBlock tskTCB
Function Documentation
__freertos_evr_on_task_switched_in()
void __freertos_evr_on_task_switched_in (void * ptTCB, uint32_t uxTopPriority)
Definition at line 225 of file perf_os_patch_freertos.c.
                                                                             {
#if defined(RTE_Compiler_EventRecorder)
  EventRecord2(EvtFreeRTOSTasks_TaskSwitchedIn, (uint32_t)ptTCB, uxTopPriority);
#else
  (void)pxCurrentTCB;
  (void)uxTopPriority;
#endif
    
    __on_context_switch_in(((TCB_t *)ptTCB)->pxStack);
}
References __on_context_switch_in(), EvtFreeRTOSTasks_TaskSwitchedIn, and pxCurrentTCB.
__freertos_evr_on_task_switched_out()
void __freertos_evr_on_task_switched_out (void * ptTCB)
Definition at line 213 of file perf_os_patch_freertos.c.
                                                       {
#if defined(RTE_Compiler_EventRecorder)
  EventRecord2(EvtFreeRTOSTasks_TaskSwitchedOut, (uint32_t)ptTCB, 0U);
#else
  (void)pxCurrentTCB;
#endif
    
    __on_context_switch_out(((TCB_t *)ptTCB)->pxStack);
    
}
References __on_context_switch_out(), EvtFreeRTOSTasks_TaskSwitchedOut, and pxCurrentTCB.
__on_context_switch_in()
void __on_context_switch_in (uint32_t * pwStack)
Note
if you aren't using perf_counter inside KEIL with RTE, please create ! a header file called `Pre_Include_Global.h`, copy the following ! content into the header file and and put following option ! to your command line (supposing you are using arm compiler 6): ! -include `Pre_Include_Global.h`
update all agents
Definition at line 646 of file perf_counter.c.
{
    struct __task_cycle_info_t *ptRootAgent = (struct __task_cycle_info_t *)pwStack;
    uint64_t dwTimeStamp = get_system_ticks();
    
    ptRootAgent->lLastTimeStamp = dwTimeStamp;
    ptRootAgent->tInfo.hwActiveCount++;
    if (MAGIC_WORD_AGENT_LIST_VALID == ptRootAgent->wMagicWord) {
        task_cycle_info_agent_t *ptAgent = ptRootAgent->tList.ptNext;
        while(NULL != ptAgent) {
            if (NULL != ptAgent->ptInfo) {
                if (ptAgent->ptInfo->bEnabled) {
                    ptAgent->ptInfo->hwActiveCount++;
                }
            }
            ptAgent = ptAgent->ptNext;
        }
    }
}
Referenced by __freertos_evr_on_task_switched_in().
__on_context_switch_out()
void __on_context_switch_out (uint32_t * pwStack)
update all agents
Definition at line 668 of file perf_counter.c.
{
    struct __task_cycle_info_t *ptRootAgent = (struct __task_cycle_info_t *)pwStack;
    int64_t lCycleUsed = get_system_ticks() - ptRootAgent->lLastTimeStamp;
    
    ptRootAgent->tInfo.nUsedRecent = lCycleUsed;
    ptRootAgent->tInfo.lUsedTotal += lCycleUsed;
    
    if (MAGIC_WORD_AGENT_LIST_VALID == ptRootAgent->wMagicWord) {
        task_cycle_info_agent_t *ptAgent = ptRootAgent->tList.ptNext;
        while(NULL != ptAgent) {
            if (NULL != ptAgent->ptInfo) {
                if (ptAgent->ptInfo->bEnabled) {
                    ptAgent->ptInfo->nUsedRecent = lCycleUsed;
                    ptAgent->ptInfo->lUsedTotal += lCycleUsed;
                }
            }
            ptAgent = ptAgent->ptNext;
        }
    }
}
Referenced by __freertos_evr_on_task_switched_out().
get_rtos_task_cycle_info()
task_cycle_info_t * get_rtos_task_cycle_info (void)
Definition at line 237 of file perf_os_patch_freertos.c.
{
    return &(((struct __task_cycle_info_t *)pxCurrentTCB->pxStack)->tInfo);
}
References pxCurrentTCB, and tskTaskControlBlock::pxStack.
Variable Documentation
pxCurrentTCB
PRIVILEGED_DATA TCB_t* volatile pxCurrentTCB [extern]
Referenced by __freertos_evr_on_task_switched_in(), __freertos_evr_on_task_switched_out(), and get_rtos_task_cycle_info().